linkedIn: https://www.linkedin.com/in/spencer-young-4771b037/
email: spjy@hawaii.edu
github: http://github.com/spjy
skills:
  software:
    - HTML
    - CSS
    - JavaScript
    - C
    - C++
    - Node.js
    - Python
    - Golang
  engineering:
    - SystemVerilog
    - LogicWorks
    - Oscilloscope
    - Soldering
  frameworks & tools:
    - React
    - Redux
    - Vue
    - Git
    - Unix
    - Docker
    - REST
    - Jira
