linkedIn: https://www.linkedin.com/in/spencer-young-4771b037/
email: spjy@hawaii.edu
github: http://github.com/spjy
skills:
  software:
    - HTML/CSS
    - TypeScript
    - Python
  engineering:
    - Oscilloscope
    - Soldering
  frameworks:
    - React
    - Redux
    - RxJS
    - Vue
    - Git
    - Linux
    - Docker
    - REST
    - JIRA
  coursework:
    - Programming in C/C++
    - Digital Design (VHDL)
    - Computer Architecture (ARMv8, SystemVerilog)
    - Discrete Math
    - Signals & Systems
    - Microelectronics
    - Electromagnetism
    - AC/DC Circuit Analysis
    - Probability & Statistics
    - Machine Learning
    - Algorithms & Data Structures
    - Software Engineering
    - Digital Image Processing
    - Linear Feedback & Control Systems
    - Operating Systems
